#Облегченный конфиг для заливки tft прошивки. Столкнулся с проблемой что с основным конфигом прошивка на экран корректно не заливается (веротяно проблемы с производительностью)
substitutions:
  name: nsp_bathroom
  device_name: "nsp_bathroom"
  prefix: "nsp_bathroom" 
# Enable logging
esphome:
  name: $name
  comment: $device_name
  on_boot:
    priority: 601
    then:
      - lambda: id(disp1).send_command_printf("DRAKJHSUYDGBNCJHGJKSHBDN");
logger:
ota:
  password: "33ba8da3afc16873ef9b270235710659"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

external_components:
  - source: github://pr#2956
    components: [nextion]
    refresh: 1h
esp32:
  board: esp32dev
#заливаем прошивку по правой клавише
binary_sensor:
  - platform: gpio
    name: $device_name Right Button
    pin:
      number: 27
      inverted: true
    on_click:
        - lambda: 'id(disp1)->upload_tft();'   
sensor:
  # Internal temperature sensor, adc value
  - platform: adc
    id: ntc_source
    pin: 38
    update_interval: 10s
    attenuation: 11db    
  - platform: resistance
    id: resistance_sensor
    sensor: ntc_source
    configuration: DOWNSTREAM
    resistor: 11.2kOhm
  # Internal temperature sensor, resistance to temperature (calculation)
  - platform: ntc
    id: temperature
    sensor: resistance_sensor
    calibration:
      b_constant: 3950
      reference_temperature: 25°C
      reference_resistance: 10kOhm
    name: $device_name Temperature
    on_value:
        - lambda: id(disp1).set_component_text_printf("main.t4", "%.1f C", id(temperature).state);
  # Pin 4 always needs to be on to power up the display
switch:
  - platform: gpio
    name: "ScreenPower"
    id: screen_power
    pin:
      number: 4
      inverted: true
    restore_mode: ALWAYS_ON
number:
  platform: template
  name: $device_name Brightness
  id: brightness
  entity_category: config
  unit_of_measurement: '%'
  min_value: 0
  max_value: 100
  step: 1
  initial_value: 30
  set_action:
    then:
      - lambda: 'id(disp1).set_backlight_brightness(x/100);'

# Configure the internal bleeper
output:
  - platform: ledc
    id: buzzer_out
    pin:
      number: 21

# Enable ringtone music support
rtttl:
  id: buzzer
  output: buzzer_out

# Configure UART for communicating with the screen
uart:
  id: tf_uart
  tx_pin: 16
  rx_pin: 17
  baud_rate: 115200

# Configure the screen itself
display:
  - platform: nextion
    id: disp1
    uart_id: tf_uart
    tft_url: https://github.com/Lastik-Lastikov/wb-nsp/blob/1932d98a9c7889467ab4a2f254a76198e5e3c097/bathroom.tft
    on_setup:
      then:
        - number.set:
            id: brightness
            value: 30
